In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
d = tf.multiply(a,b)
e = tf.add(c,b)
f = tf.subtract(d,e)
sess = tf.Session()
outs = sess.run(f)
sess.close()
print("outs = {}".format(outs))

outs = 5


In [4]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.multiply(a,b)
d = tf.pow(c,2)
e = tf.divide(d,a)
with tf.Session() as sess:
    fetches = [a,b,c,d,e]
    outs = sess.run(fetches)
print("outs = {}".format(outs))

outs = [5, 2, 10, 100, 20.0]


In [5]:
a = tf.constant([[1,2,3],[4,5,6]])
print(a.get_shape())

(2, 3)


In [6]:
x = tf.constant([1,0,1])
print(x.get_shape())

(3,)


In [7]:
b = tf.matmul(a,x)

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [2,3], [3].

In [8]:
x = tf.expand_dims(x,1)
print(x.get_shape())

(3, 1)


In [10]:
b = tf.matmul(a,x)
print(b)
sess = tf.InteractiveSession()
print("matmul : \n {}\n".format(b.eval()))

Tensor("MatMul_2:0", shape=(2, 1), dtype=int32)
matmul : 
 [[ 4]
 [10]]



In [11]:
import numpy as np

x = np.array([1,0,1])
print(x.shape)

(3,)


In [13]:
a = tf.constant([[1,2,3],[4,5,6]])
x = x[:,np.newaxis]
print(x.shape)
b = tf.matmul(a,x)
print("matmul : \n {}\n".format(b.eval()))

(3, 1)
matmul : 
 [[ 4]
 [10]]



In [14]:
val = tf.random_normal((1,5),0,1)
var = tf.Variable(val, name='var')
print("pre run : \n{}".format(var))

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var = sess.run(var)
print("\npost_var : \n{}".format(post_var))

pre run : 
<tf.Variable 'var:0' shape=(1, 5) dtype=float32_ref>

post_var : 
[[ 0.61460567  0.1092485   1.121723   -1.0570486  -1.2664924 ]]


In [18]:
x_data = np.random.randn(5,10)
w_data = np.random.randn(10,1)
#print(x_data, w_data)

with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=(5,10))
    w = tf.placeholder(tf.float32, shape=(10,1))
    b = tf.fill((5,1), -1.)
    xw = tf.matmul(x,w)
    xwb = xw + b    
    s = tf.reduce_max(xwb)
    with tf.Session() as sess:
        outs = sess.run([x, w, s], feed_dict={x:x_data, w:w_data})
print("x = \n{}\nw = \n{}\ns = {}".format(outs[0], outs[1], outs[2]))

x = 
[[-0.13904986  0.1457575  -2.0358982   0.3355342   0.04924482 -1.3103861
   0.46964166  0.14723343 -1.7080488  -0.19066322]
 [ 1.7308376   0.01919317  1.3128606   2.0904193   0.8217379   1.1214676
   0.98623407 -0.7008952  -1.1281167  -0.65573317]
 [ 0.18813722 -0.85544217  1.2795955   1.3949472  -0.11653471  0.7736363
  -0.27573973  0.79115444 -1.4169803  -0.7595182 ]
 [ 0.51917475  1.1974826   0.53466034  1.3002193   0.71692574  2.8679278
   0.6873461  -0.17190193 -0.10661603  0.5841518 ]
 [ 0.35055232  1.0275059   0.48710632  0.17798144  1.4624175  -0.11168709
  -1.0732871   0.27414986  1.5005846   0.8215995 ]]
w = 
[[-2.4270175 ]
 [ 0.58395886]
 [-1.5414184 ]
 [-0.50682545]
 [ 0.7650509 ]
 [-1.135181  ]
 [-0.30305967]
 [ 0.3843848 ]
 [ 1.3322821 ]
 [ 0.6218474 ]]
s = 2.0945539474487305


In [54]:
def standRegres(xArr, yArr):
    xMat = np.mat(xArr)
    yMat = np.mat(yArr).T
    
    xTx = xMat.T*xMat
    if np.linalg.det(xTx) == 0.0:
        print("This matrix is singular")
        return
    ws = xTx.I * (xMat.T*yMat)
    return ws

xArr = np.array([[1, 2, 3],[1, 3, 4]])
yArr = np.array([[2, 3]])

standRegres(xArr, yArr)

matrix([[ 0.5],
        [-0.5],
        [-1.5]])

In [53]:
x_data = np.array([[1, 2, 3],[1, 3, 4]])
y_data = np.array([[2, 3]])

with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=[None,3])
    y = tf.placeholder(tf.float32, shape=None)
    
    w = tf.Variable([[0,0,0]], dtype=tf.float32, name='weight')
    #b = tf.Variable(0, dtype=tf.float32, name='bias')
    
    y_hat = tf.matmul(w, tf.transpose(x))# + b
    
    loss = tf.reduce_mean(tf.square(y - y_hat))
    #cost = tf.Variable(loss, dtype=tf.float32, name='cost')
    
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.005)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(100000):
            sess.run(train, feed_dict={x:x_data, y:y_data})
            if (step % 5000 == 0):
                print(step, sess.run([w]))
        print(step, sess.run([w]))

0 [array([[0.025, 0.065, 0.09 ]], dtype=float32)]
5000 [array([[-0.26317695,  0.61448556,  0.35131398]], dtype=float32)]
10000 [array([[-0.32262057,  0.65868396,  0.33608952]], dtype=float32)]
15000 [array([[-0.33170453,  0.6654359 ,  0.33376473]], dtype=float32)]
20000 [array([[-0.33309162,  0.66646445,  0.3334114 ]], dtype=float32)]
25000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
30000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
35000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
40000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
45000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
50000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
55000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
60000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
65000 [array([[-0.33330128,  0.6666064 ,  0.33336762]], dtype=float32)]
70000 [array([[

In [51]:
x_data = np.array([[2, 3],[3, 4]])
w_data = np.array([[0.66660666, 0.33336723]])
b_data = -0.33330047
y_data = np.array([[2, 3]])
np.matmul(w_data, x_data) + b_data

array([[2.00001454, 2.99998843]])